# Generated by Django 5.2.2 on 2025-06-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='current_approval_level',
            field=models.CharField(choices=[('director_pending', 'Land Director Approval'), ('secretary_pending', 'Secretary Approval'), ('deputy_mayor_pending', 'Deputy Mayor Approval'), ('mayor_pending', 'Mayor Approval'), ('completed', 'Approval Process Completed'), ('rejected', 'Approval Process Rejected')], default='director_pending', max_length=50),
        ),
        migrations.AddField(
            model_name='approval',
            name='director_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='mayor_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='secretary_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='deputy_mayor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='deputy_mayor_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='deputy_mayor_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='deputy_mayor_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='director_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='director_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='director_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='director_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='mayor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='mayor_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='mayor_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='mayor_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='secretary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='secretary_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='secretary_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='secretary_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
