# Generated by Django 5.2.2 on 2025-06-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0002_approval_current_approval_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='landmapping',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='landsurvey',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='surveypayment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taxpayment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
