# Generated by Django 5.2 on 2025-06-09 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0005_approval_rejection_date_approval_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='return_step',
            field=models.CharField(blank=True, choices=[('registration', 'Land Registration'), ('survey_payment', 'Survey Payment'), ('land_survey', 'Land Survey'), ('tax_payment', 'Tax Payment'), ('land_mapping', 'Land Mapping'), ('certificate_generated', 'Certificate Generated')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landregistration',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='land_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='landregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
