# Generated by Django 5.2.1 on 2025-07-12 07:43

import django.db.models.deletion
import django.utils.timezone
import land_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0007_add_registration_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='landregistration',
            name='buyer_full_name',
            field=models.CharField(max_length=255, validators=[land_management.models.validate_alpha_name]),
        ),
        migrations.AlterField(
            model_name='landregistration',
            name='buyer_national_id',
            field=models.CharField(max_length=50, validators=[land_management.models.validate_national_id]),
        ),
        migrations.AlterField(
            model_name='landregistration',
            name='buyer_phone',
            field=models.CharField(max_length=20, validators=[land_management.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='landregistration',
            name='land_size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='landregistration',
            name='seller_full_name',
            field=models.CharField(max_length=255, validators=[land_management.models.validate_alpha_name]),
        ),
        migrations.AlterField(
            model_name='landregistration',
            name='seller_national_id',
            field=models.CharField(max_length=50, validators=[land_management.models.validate_national_id]),
        ),
        migrations.AlterField(
            model_name='landregistration',
            name='seller_phone',
            field=models.CharField(max_length=20, validators=[land_management.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='landsurvey',
            name='parcel_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='landsurvey',
            name='survey_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_resets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
